project_id = "wyvaygkvuhayqyphngab"

[auth.email.template.recovery]
subject = "Reset your password â€“ Konfetti"
content_path = "./supabase/templates/recovery.html"

[functions.send-matchmaking-notifications]
verify_jwt = false

[functions.event-request-notification]
verify_jwt = false
